### ISSUE TITLE
Make OnSignal work on windows

### ISSUE THREAD

**Issue by bayerj** [BRML/climin#35]
There is an issue with FORTAN libraries replacing signal handlers and not being able to recover them:

  http://stackoverflow.com/questions/15457786/ctrl-c-crashes-python-after-importing-scipy-stats

The solution is to

Add to ``climin/__init__.py``:

    if sys.platform == 'win32':
      basepath = imp.find_module('numpy')[1]
      ctypes.CDLL(os.path.join(basepath, 'core', 'libmmd.dll'))
      ctypes.CDLL(os.path.join(basepath, 'core', 'libifcoremd.dll'))

And then extend ``OnSignal`` with 

    import win32api
    win32api.SetConsoleCtrlHandler(self._console_ctrl_handler, 1)

in the windows case.

After that, climin has to be imported before scipy by the user.

**Comment by msoelch** [comment]
Has been added to __init__.py.
